on:
  push:
    branches:
      - main
  workflow_dispatch:
name: Sentry
jobs:
  sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: yagiz-nb
          SENTRY_PROJECT: yagiz-co
        with:
          environment: production
